<?php


namespace app\home\model;


class BaseMember extends BaseModel
{
    protected function base($query){
        return $query->where('member_id',$this->member_id);
    }

    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
    }
}